guvision_utils: SimpleRectangle Class Reference
SimpleRectangle Class Reference
#include <SimpleShapes.h>
Public Member Functions
SimpleRectangle ()
SimpleRectangle (const SimpleRectangle &rect)
SimpleRectangle (int left, int right, int top, int bottom)
bool Overlaps (const SimpleRectangle &r)
bool Intersection (const SimpleRectangle &r, SimpleRectangle &intersection)
SimpleRectangle Union (const SimpleRectangle &r)
SimpleRectangle & operator= (const SimpleRectangle &r)
int Area () OVERRIDE
int Width ()
int Height ()
GUPoint< short > Center ()
int DistannceTo (const SimpleRectangle &rec)
virtual void Copy (SimpleShape *rectangle) const OVERRIDE
virtual short shapePointIntersection (const GUPoint< short > &, GUPoint< short > *) const OVERRIDE
virtual bool insideShape (const GUPoint< int > &point) const OVERRIDE
int left () const
int right () const
int top () const
int bottom () const
void setLeft (int left)
void setRight (int right)
void setTop (int top)
void setBottom (int bottom)
Public Member Functions inherited from SimpleShape
SimpleShape ()
SimpleShape (const SimpleShape &shape)
SimpleShape & operator= (const SimpleShape &shape)
virtual ~SimpleShape ()
virtual std::vector< GUPoint< short > > intersections (SimpleShape &)
Detailed Description
Definition at line 598 of file SimpleShapes.h.
Constructor & Destructor Documentation
SimpleRectangle() [1/3]
SimpleRectangle::SimpleRectangle () inline
Definition at line 601 of file SimpleShapes.h.
SimpleRectangle() [2/3]
SimpleRectangle::SimpleRectangle (const SimpleRectangle & rect) inline
Definition at line 602 of file SimpleShapes.h.
SimpleRectangle() [3/3]
SimpleRectangle::SimpleRectangle (int left, int right, int top, int bottom) inline
Definition at line 603 of file SimpleShapes.h.
References bottom(), left(), right(), and top().
Member Function Documentation
Area()
int SimpleRectangle::Area () inline virtual
Implements SimpleShape.
Definition at line 651 of file SimpleShapes.h.
References bottom(), left(), right(), and top().
bottom()
int SimpleRectangle::bottom () const inline
Definition at line 699 of file SimpleShapes.h.
Referenced by SimpleRectangle(), Area(), Center(), DistannceTo(), Height(), Intersection(), Overlaps(), setBottom(), and Union().
Center()
GUPoint< short > SimpleRectangle::Center () inline
Definition at line 663 of file SimpleShapes.h.
References bottom(), left(), right(), top(), GUPoint< T >::x, and GUPoint< T >::y.
Copy()
virtual void SimpleRectangle::Copy (SimpleShape * rectangle) const inline virtual
Implements SimpleShape.
Definition at line 682 of file SimpleShapes.h.
DistannceTo()
int SimpleRectangle::DistannceTo (const SimpleRectangle & rec) inline
Definition at line 671 of file SimpleShapes.h.
References bottom(), left(), MIN, Overlaps(), right(), and top().
Height()
int SimpleRectangle::Height () inline
Definition at line 659 of file SimpleShapes.h.
References bottom(), and top().
insideShape()
virtual bool SimpleRectangle::insideShape (const GUPoint< int > & point) const inline virtual
Implements SimpleShape.
Definition at line 690 of file SimpleShapes.h.
Intersection()
bool SimpleRectangle::Intersection (const SimpleRectangle & r, SimpleRectangle & intersection) inline
Definition at line 629 of file SimpleShapes.h.
References bottom(), left(), MAX, MIN, Overlaps(), right(), setBottom(), setLeft(), setRight(), setTop(), and top().
left()
int SimpleRectangle::left () const inline
Definition at line 696 of file SimpleShapes.h.
Referenced by SimpleRectangle(), Area(), Center(), DistannceTo(), Intersection(), Overlaps(), setLeft(), Union(), and Width().
operator=()
SimpleRectangle & SimpleRectangle::operator= (const SimpleRectangle & r) inline
Definition at line 645 of file SimpleShapes.h.
Overlaps()
bool SimpleRectangle::Overlaps (const SimpleRectangle & r) inline
Definition at line 624 of file SimpleShapes.h.
References bottom(), left(), right(), and top().
Referenced by DistannceTo(), and Intersection().
right()
int SimpleRectangle::right () const inline
Definition at line 697 of file SimpleShapes.h.
Referenced by SimpleRectangle(), Area(), Center(), DistannceTo(), Intersection(), Overlaps(), setRight(), Union(), and Width().
setBottom()
void SimpleRectangle::setBottom (int bottom) inline
Definition at line 703 of file SimpleShapes.h.
References bottom().
Referenced by Intersection().
setLeft()
void SimpleRectangle::setLeft (int left) inline
Definition at line 700 of file SimpleShapes.h.
References left().
Referenced by Intersection().
setRight()
void SimpleRectangle::setRight (int right) inline
Definition at line 701 of file SimpleShapes.h.
References right().
Referenced by Intersection().
setTop()
void SimpleRectangle::setTop (int top) inline
Definition at line 702 of file SimpleShapes.h.
References top().
Referenced by Intersection().
shapePointIntersection()
virtual short SimpleRectangle::shapePointIntersection (const GUPoint< short > & , GUPoint< short > *) const inline virtual
Implements SimpleShape.
Definition at line 688 of file SimpleShapes.h.
top()
int SimpleRectangle::top () const inline
Definition at line 698 of file SimpleShapes.h.
Referenced by SimpleRectangle(), Area(), Center(), DistannceTo(), Height(), Intersection(), Overlaps(), setTop(), and Union().
Union()
SimpleRectangle SimpleRectangle::Union (const SimpleRectangle & r) inline
Definition at line 639 of file SimpleShapes.h.
References bottom(), left(), right(), and top().
Width()
int SimpleRectangle::Width () inline
Definition at line 655 of file SimpleShapes.h.
References left(), and right().
The documentation for this class was generated from the following file:
SimpleShapes.h