guvision_utils: SimpleShape Class Reference
SimpleShape Class Reference abstract
super class for other shapes
#include <SimpleShapes.h>
Public Member Functions
SimpleShape ()
SimpleShape (const SimpleShape &shape)
SimpleShape & operator= (const SimpleShape &shape)
virtual short shapePointIntersection (const GUPoint< short > &p, GUPoint< short > *pIntersection) const =0
virtual void Copy (SimpleShape *shape) const =0
virtual bool insideShape (const GUPoint< int > &point) const =0
virtual ~SimpleShape ()
virtual int Area ()=0
virtual std::vector< GUPoint< short > > intersections (SimpleShape &)
Detailed Description
super class for other shapes
Definition at line 137 of file SimpleShapes.h.
Constructor & Destructor Documentation
SimpleShape() [1/2]
SimpleShape::SimpleShape () inline
Definition at line 139 of file SimpleShapes.h.
SimpleShape() [2/2]
SimpleShape::SimpleShape (const SimpleShape & shape) inline
Definition at line 140 of file SimpleShapes.h.
References Copy().
~SimpleShape()
virtual SimpleShape::~SimpleShape () inline virtual
Definition at line 145 of file SimpleShapes.h.
Member Function Documentation
Area()
virtual int SimpleShape::Area () pure virtual
Implemented in SimpleCircle, SimpleLine, and SimpleRectangle.
Copy()
virtual void SimpleShape::Copy (SimpleShape * shape) const pure virtual
Implemented in SimpleCircle, SimpleLine, and SimpleRectangle.
Referenced by SimpleShape(), and operator=().
insideShape()
virtual bool SimpleShape::insideShape (const GUPoint< int > & point) const pure virtual
Implemented in SimpleCircle, SimpleLine, and SimpleRectangle.
intersections()
virtual std::vector< GUPoint< short > > SimpleShape::intersections (SimpleShape &) inline virtual
Reimplemented in SimpleLine.
Definition at line 147 of file SimpleShapes.h.
Referenced by SimpleLine::intersections().
operator=()
SimpleShape & SimpleShape::operator= (const SimpleShape & shape) inline
Definition at line 141 of file SimpleShapes.h.
References Copy().
shapePointIntersection()
virtual short SimpleShape::shapePointIntersection (const GUPoint< short > & p, GUPoint< short > * pIntersection) const pure virtual
Implemented in SimpleRectangle, SimpleCircle, and SimpleLine.
The documentation for this class was generated from the following file:
SimpleShapes.h