guvision_utils: SimpleCircle Class Reference
SimpleCircle Class Reference
#include <SimpleShapes.h>
Public Member Functions
SimpleCircle ()
SimpleCircle (GUPoint< short > center, double radius)
SimpleCircle (short x, short y, double radius)
SimpleCircle (const SimpleCircle &shape)
SimpleCircle (const GUPoint< short > *p1, const GUPoint< short > *p2, const GUPoint< short > *p3)
SimpleCircle & operator= (const SimpleCircle &shape)
virtual short shapePointIntersection (const GUPoint< short > &p, GUPoint< short > *pIntersection) const OVERRIDE
virtual bool insideShape (const GUPoint< int > &) const OVERRIDE
virtual void Copy (SimpleShape *circle) const OVERRIDE
void FindCircle (const GUPoint< short > *p1, const GUPoint< short > *p2, const GUPoint< short > *p3)
GUPoint< short > GetCenter () const
short GetRadius () const
int Area () OVERRIDE
void setCenter (GUPoint< short > center)
void setRadius (double radius)
Public Member Functions inherited from SimpleShape
SimpleShape ()
SimpleShape (const SimpleShape &shape)
SimpleShape & operator= (const SimpleShape &shape)
virtual ~SimpleShape ()
virtual std::vector< GUPoint< short > > intersections (SimpleShape &)
Detailed Description
Definition at line 150 of file SimpleShapes.h.
Constructor & Destructor Documentation
SimpleCircle() [1/5]
SimpleCircle::SimpleCircle () inline
Definition at line 153 of file SimpleShapes.h.
SimpleCircle() [2/5]
SimpleCircle::SimpleCircle (GUPoint< short > center, double radius) inline
Definition at line 154 of file SimpleShapes.h.
SimpleCircle() [3/5]
SimpleCircle::SimpleCircle (short x, short y, double radius) inline
Definition at line 159 of file SimpleShapes.h.
SimpleCircle() [4/5]
SimpleCircle::SimpleCircle (const SimpleCircle & shape) inline
Definition at line 164 of file SimpleShapes.h.
SimpleCircle() [5/5]
SimpleCircle::SimpleCircle (const GUPoint< short > * p1, const GUPoint< short > * p2, const GUPoint< short > * p3) inline
Definition at line 166 of file SimpleShapes.h.
References FindCircle().
Member Function Documentation
Area()
int SimpleCircle::Area () inline virtual
Implements SimpleShape.
Definition at line 206 of file SimpleShapes.h.
References GetRadius(), and PI.
Copy()
virtual void SimpleCircle::Copy (SimpleShape * circle) const inline virtual
Implements SimpleShape.
Definition at line 184 of file SimpleShapes.h.
Referenced by operator=().
FindCircle()
void SimpleCircle::FindCircle (const GUPoint< short > * p1, const GUPoint< short > * p2, const GUPoint< short > * p3) inline
Definition at line 188 of file SimpleShapes.h.
Referenced by SimpleCircle().
GetCenter()
GUPoint< short > SimpleCircle::GetCenter () const inline
Definition at line 204 of file SimpleShapes.h.
GetRadius()
short SimpleCircle::GetRadius () const inline
Definition at line 205 of file SimpleShapes.h.
Referenced by Area().
insideShape()
virtual bool SimpleCircle::insideShape (const GUPoint< int > &) const inline virtual
Implements SimpleShape.
Definition at line 183 of file SimpleShapes.h.
operator=()
SimpleCircle & SimpleCircle::operator= (const SimpleCircle & shape) inline
Definition at line 169 of file SimpleShapes.h.
References Copy().
setCenter()
void SimpleCircle::setCenter (GUPoint< short > center) inline
Definition at line 209 of file SimpleShapes.h.
setRadius()
void SimpleCircle::setRadius (double radius) inline
Definition at line 213 of file SimpleShapes.h.
shapePointIntersection()
virtual short SimpleCircle::shapePointIntersection (const GUPoint< short > & p, GUPoint< short > * pIntersection) const inline virtual
Implements SimpleShape.
Definition at line 170 of file SimpleShapes.h.
References GUPoint< T >::Length().
The documentation for this class was generated from the following file:
SimpleShapes.h