guvision_utils: SimpleLine Class Reference
SimpleLine Class Reference
#include <SimpleShapes.h>
Public Member Functions
SimpleLine ()
SimpleLine (const SimpleLine &line)
SimpleLine (const GUPoint< short > *p1, const GUPoint< short > *p2)
SimpleLine (const GUPoint< short > &p1, const GUPoint< short > &p2)
SimpleLine & operator= (const SimpleLine &shape)
short GetLength () const
double length () const
GUPoint< short > UnitVector () const
virtual bool insideShape (const GUPoint< int > &) const OVERRIDE
short shapePointIntersection (const GUPoint< short > &p, GUPoint< short > *pIntersection) const OVERRIDE
short distanceToLineSegment (const GUPoint< short > &p, GUPoint< short > *pIntersection=NULLPTR) const
short distanceToLineSegment (GUPoint< short > *pIntersection=NULLPTR) const
int Area () OVERRIDE
virtual void Copy (SimpleShape *Line) const OVERRIDE
float Gradiant () const
double angle () const
Gives the angle of the line.
int angleToX () const
GUPoint< short > pointWithSmallestY () const
GUPoint< short > pointWithLargestY () const
GUPoint< short > lowestPoint () const
GUPoint< short > highestPoint () const
GUPoint< short > leftPoint () const
GUPoint< short > rightPoint () const
GUPoint< short > pointFromX (short x)
Extrapolate point on line from given x.
GUPoint< short > pointFromY (short y)
Extrapolate point on line from given y.
std::vector< GUPoint< short > > intersections (SimpleShape &shape) OVERRIDE
bool intersects (SimpleLine line)
std::vector< GUPoint< short > > lineIntersection (SimpleLine &l) const
Calculate the intersection of this line with the given line.
SimpleLine normalToOrigin () const
Calculates a line normal to the current line that passes through the origin.
GUPoint< short > distanceAlongeLine (int distance)
Find the point a certain distance from the start point along the line.
SimpleLine rotated (double radians)
SimpleLine clockwise rotation around the center point Assumes screen coords (0, 0) in the top left etc.
SimpleLine operator+ (GUPoint< short > p)
SimpleLine operator- (GUPoint< short > p)
Public Member Functions inherited from SimpleShape
SimpleShape ()
SimpleShape (const SimpleShape &shape)
SimpleShape & operator= (const SimpleShape &shape)
virtual ~SimpleShape ()
Static Public Member Functions
static GUPoint< short > dotLineIntersection (short x, short y, short lx0, short ly0, short lx1, short ly1)
Public Attributes
GUPoint< short > start
GUPoint< short > end
Detailed Description
Definition at line 288 of file SimpleShapes.h.
Constructor & Destructor Documentation
SimpleLine() [1/4]
SimpleLine::SimpleLine () inline
Definition at line 291 of file SimpleShapes.h.
Referenced by normalToOrigin(), and rotated().
SimpleLine() [2/4]
SimpleLine::SimpleLine (const SimpleLine & line) inline
Definition at line 292 of file SimpleShapes.h.
SimpleLine() [3/4]
SimpleLine::SimpleLine (const GUPoint< short > * p1, const GUPoint< short > * p2) inline
Definition at line 293 of file SimpleShapes.h.
SimpleLine() [4/4]
SimpleLine::SimpleLine (const GUPoint< short > & p1, const GUPoint< short > & p2) inline
Definition at line 294 of file SimpleShapes.h.
Member Function Documentation
angle()
double SimpleLine::angle () const inline
Gives the angle of the line.
Returns
angle between 0 and PI
Definition at line 382 of file SimpleShapes.h.
References end, length(), and start.
Referenced by normalToOrigin().
angleToX()
int SimpleLine::angleToX () const inline
Definition at line 389 of file SimpleShapes.h.
References end, and start.
Area()
int SimpleLine::Area () inline virtual
Implements SimpleShape.
Definition at line 351 of file SimpleShapes.h.
Copy()
virtual void SimpleLine::Copy (SimpleShape * Line) const inline virtual
Implements SimpleShape.
Definition at line 365 of file SimpleShapes.h.
References end, and start.
Referenced by operator=().
distanceAlongeLine()
GUPoint< short > SimpleLine::distanceAlongeLine (int distance) inline
Find the point a certain distance from the start point along the line.
Parameters
distance from the start of the line
Returns
The point lying on this line
Definition at line 541 of file SimpleShapes.h.
References end, length(), and start.
distanceToLineSegment() [1/2]
short SimpleLine::distanceToLineSegment (const GUPoint< short > & p, GUPoint< short > * pIntersection = NULLPTR) const inline
Definition at line 331 of file SimpleShapes.h.
References GUPoint< T >::Distance(), end, shapePointIntersection(), and start.
Referenced by distanceToLineSegment().
distanceToLineSegment() [2/2]
short SimpleLine::distanceToLineSegment (GUPoint< short > * pIntersection = NULLPTR) const inline
Definition at line 347 of file SimpleShapes.h.
References distanceToLineSegment().
dotLineIntersection()
static GUPoint< short > SimpleLine::dotLineIntersection (short x, short y, short lx0, short ly0, short lx1, short ly1) inline static
Definition at line 355 of file SimpleShapes.h.
GetLength()
short SimpleLine::GetLength () const inline
Definition at line 297 of file SimpleShapes.h.
References end, GUPoint< T >::Length(), and start.
Gradiant()
float SimpleLine::Gradiant () const inline
Definition at line 371 of file SimpleShapes.h.
References end, and start.
highestPoint()
GUPoint< short > SimpleLine::highestPoint () const inline
Returns
the point whose y value is furtherest to 0
Definition at line 426 of file SimpleShapes.h.
References end, and start.
Referenced by pointFromY().
insideShape()
virtual bool SimpleLine::insideShape (const GUPoint< int > &) const inline virtual
Implements SimpleShape.
Definition at line 305 of file SimpleShapes.h.
intersections()
std::vector< GUPoint< short > > SimpleLine::intersections (SimpleShape & shape) inline virtual
Reimplemented from SimpleShape.
Definition at line 477 of file SimpleShapes.h.
References SimpleShape::intersections(), and lineIntersection().
intersects()
bool SimpleLine::intersects (SimpleLine line) inline
Definition at line 489 of file SimpleShapes.h.
References end, and start.
leftPoint()
GUPoint< short > SimpleLine::leftPoint () const inline
Returns
the point whose x value is closest to 0
Definition at line 436 of file SimpleShapes.h.
References end, and start.
Referenced by pointFromX().
length()
double SimpleLine::length () const inline
Definition at line 298 of file SimpleShapes.h.
References end, GUPoint< T >::Length(), and start.
Referenced by angle(), distanceAlongeLine(), and UnitVector().
lineIntersection()
std::vector< GUPoint< short > > SimpleLine::lineIntersection (SimpleLine & l) const inline
Calculate the intersection of this line with the given line.
Parameters
l The line that this line intersects with
Returns
The point of intersection
Definition at line 503 of file SimpleShapes.h.
References end, and start.
Referenced by intersections(), normalToOrigin(), and shapePointIntersection().
lowestPoint()
GUPoint< short > SimpleLine::lowestPoint () const inline
Returns
the point whose y value is closest to 0
Definition at line 416 of file SimpleShapes.h.
References end, and start.
Referenced by pointFromY().
normalToOrigin()
SimpleLine SimpleLine::normalToOrigin () const inline
Calculates a line normal to the current line that passes through the origin.
Returns
The newly calculated line
Definition at line 523 of file SimpleShapes.h.
References SimpleLine(), angle(), lineIntersection(), GUPoint< T >::x, and GUPoint< T >::y.
Referenced by shapePointIntersection().
operator+()
SimpleLine SimpleLine::operator+ (GUPoint< short > p) inline
Definition at line 580 of file SimpleShapes.h.
References end, and start.
operator-()
SimpleLine SimpleLine::operator- (GUPoint< short > p) inline
Definition at line 587 of file SimpleShapes.h.
References end, and start.
operator=()
SimpleLine & SimpleLine::operator= (const SimpleLine & shape) inline
Definition at line 295 of file SimpleShapes.h.
References Copy().
pointFromX()
GUPoint< short > SimpleLine::pointFromX (short x) inline
Extrapolate point on line from given x.
Parameters
x The x coordinate
Returns
A point that lies on the line with the given x value
Definition at line 457 of file SimpleShapes.h.
References leftPoint(), rightPoint(), GUPoint< T >::x, and GUPoint< T >::y.
pointFromY()
GUPoint< short > SimpleLine::pointFromY (short y) inline
Extrapolate point on line from given y.
Parameters
y The y coordinate
Returns
A point that lies on the line with the given y value
Definition at line 469 of file SimpleShapes.h.
References highestPoint(), lowestPoint(), GUPoint< T >::x, and GUPoint< T >::y.
pointWithLargestY()
GUPoint< short > SimpleLine::pointWithLargestY () const inline
Returns
the point whose y value is greater
Definition at line 406 of file SimpleShapes.h.
References end, and start.
pointWithSmallestY()
GUPoint< short > SimpleLine::pointWithSmallestY () const inline
Returns
the point whose y value is less
Definition at line 396 of file SimpleShapes.h.
References end, and start.
rightPoint()
GUPoint< short > SimpleLine::rightPoint () const inline
Returns
the point whose x value is furtherest to 0
Definition at line 446 of file SimpleShapes.h.
References end, and start.
Referenced by pointFromX().
rotated()
SimpleLine SimpleLine::rotated (double radians) inline
SimpleLine clockwise rotation around the center point Assumes screen coords (0, 0) in the top left etc.
Returns
The newly rotated line
Definition at line 553 of file SimpleShapes.h.
References SimpleLine(), end, and start.
shapePointIntersection()
short SimpleLine::shapePointIntersection (const GUPoint< short > & p, GUPoint< short > * pIntersection) const inline virtual
Implements SimpleShape.
Definition at line 310 of file SimpleShapes.h.
References end, GUPoint< T >::Length(), lineIntersection(), normalToOrigin(), SQUARE, and start.
Referenced by distanceToLineSegment().
UnitVector()
GUPoint< short > SimpleLine::UnitVector () const inline
Definition at line 300 of file SimpleShapes.h.
References end, length(), and start.
Member Data Documentation
end
GUPoint<short> SimpleLine::end
Definition at line 594 of file SimpleShapes.h.
Referenced by angle(), angleToX(), Copy(), distanceAlongeLine(), distanceToLineSegment(), GetLength(), Gradiant(), highestPoint(), intersects(), leftPoint(), length(), lineIntersection(), lowestPoint(), operator+(), operator-(), pointWithLargestY(), pointWithSmallestY(), rightPoint(), rotated(), shapePointIntersection(), and UnitVector().
start
GUPoint<short> SimpleLine::start
Definition at line 594 of file SimpleShapes.h.
Referenced by angle(), angleToX(), Copy(), distanceAlongeLine(), distanceToLineSegment(), GetLength(), Gradiant(), highestPoint(), intersects(), leftPoint(), length(), lineIntersection(), lowestPoint(), operator+(), operator-(), pointWithLargestY(), pointWithSmallestY(), rightPoint(), rotated(), shapePointIntersection(), and UnitVector().
The documentation for this class was generated from the following file:
SimpleShapes.h